ERROR_CODES = {
    # Execution Error Codes
    -102: {"text": "Syntax error", "description": "Invalid syntax was found in the command string."},
    -115: {"text": "Missing parameter", "description": "Fewer parameters were received than expected for the command."},
    -117: {"text": "Parameter type", "description": "A parameter does not match a valid type of parameter for the command."},
    -120: {"text": "Numeric invalid", "description": "One or more values in a numeric/channel list parameter is invalid."},
    -124: {"text": "Numeric value overflow", "description": "A parameter value was too large to be stored internally."},
    -125: {"text": "Numeric negative", "description": "A negative numeric parameter value was entered."},
    -126: {"text": "Numeric real", "description": "A floating point numeric parameter value was entered."},
    -127: {"text": "Channel dimension invalid", "description": "One or more entries in a channel list parameter has an invalid number of dimensions."},
    -130: {"text": "Parameter suffix", "description": "A parameter had the wrong type of units for the command."},
    -137: {"text": "Invalid header suffix", "description": "Too many numeric suffixes in the input for the specified command."},
    -150: {"text": "Invalid string data", "description": "The parameters contained an unmatched single or double quote."},
    -154: {"text": "String size", "description": "The length of the entered string exceeds the allowed limit."},
    -157: {"text": "Unmatched brackets", "description": "The parameters contain unmatched brackets."},
    -191: {"text": "Unknown parameter", "description": "One or more parameters contain an unspecified error."},
    -192: {"text": "Too many dimensions", "description": "Too many dimensions in entry."},
    -193: {"text": "No entry", "description": "There was no entry to get - the index was beyond the end of the entries."},
    -200: {"text": "Generic execution", "description": "General Execution error has occurred."},
    -211: {"text": "Trigger ignored", "description": "A trigger command was ignored because the device was not in the correct state."},
    -213: {"text": "Init ignored", "description": "An INITiate command was received but could not be executed because a measurement was already in progress."},
    -214: {"text": "Trigger deadlock", "description": "A trigger deadlock occurred due to incorrect trigger source."},
    -222: {"text": "Illegal data value", "description": "An illegal data value was provided in the command."},
    -223: {"text": "Too much data", "description": "A character string was too long to be processed."},
    -227: {"text": "Invalid function", "description": "A decibels modifier was applied to an unsupported function."},
    -230: {"text": "Data stale", "description": "A FETCh? command was received but the internal reading memory was empty."},
    -242: {"text": "Data timeout", "description": "Timed out while taking data."},
    -243: {"text": "Second function invalid", "description": "Secondary function is not enabled."},
    -318: {"text": "Can't save MAC", "description": "Could not save MAC address."},
    -319: {"text": "Can't save LAN configuration", "description": "Could not save network configuration."},
    -320: {"text": "Can't save non-volatile configuration", "description": "Could not save non-volatile configuration."},
    -330: {"text": "Self-test failed", "description": "The Meter's complete self-test failed."},
    -350: {"text": "Too many errors", "description": "The error queue is full because more than 16 errors have occurred."},
    -410: {"text": "Query interrupted", "description": "The output buffer contained data from a previous command."},
    -420: {"text": "Query unterminated", "description": "The Meter was addressed to talk but no command was received that sends data to the output buffer."},
    -430: {"text": "Query deadlocked", "description": "Too much data was generated to fit in the output buffer, causing a deadlock."},
    -440: {"text": "Query unterminated after indefinite response", "description": "A command was received in the wrong order, leaving the query unterminated."},
    -501: {"text": "RTC Time", "description": "Error setting the RTC/System time."},
    -502: {"text": "RTC Data", "description": "Error setting the RTC/System date."},
    31: {"text": "AC/DC selected while REAR inputs selected", "description": "The Front/Rear input switch was set to REAR while ac/dc current was selected via a remote command."},
    32: {"text": "Offset selected while unavailable/overrange", "description": "The B1 offset command was entered when a measurement wasn't available or the previous measurement resulted in an overload condition."},
    51: {"text": "8840 CALibration command not valid", "description": "An 8842A calibration command was entered, which is not supported."},
    71: {"text": "8840 Syntax Error", "description": "An improper command was entered."},
    200: {"text": "IG Invalid", "description": "Invalid response type from inguard."},
    201: {"text": "IG Packet size", "description": "Incorrect packet size from inguard."},
    202: {"text": "Trigger ignored", "description": "Trigger ignored."},
    203: {"text": "Configuration acknowledgement", "description": "Wrong number configuration acknowledgement."},
    222: {"text": "Parameter invalid", "description": "Invalid parameter."},
    223: {"text": "FUNC2 mismatch", "description": "Function/2nd func mismatch."},
    224: {"text": "Math mismatch", "description": "Function/math mismatch."},
    225: {"text": "Range mismatch", "description": "Function/range mismatch."},
    226: {"text": "Load fail", "description": "Measurement configuration load failed."},
    300: {"text": "GX Sync send", "description": "Inguard not responding (send)."},
    301: {"text": "GX Sync recv", "description": "Inguard not responding (recv)."},
    302: {"text": "GX Sync error", "description": "Lost sync with inguard."},
    303: {"text": "GX Port fail", "description": "Could not open guard crossing port."},
    310: {"text": "GX Ack queue full", "description": "Acknowledgement queue full."},
    311: {"text": "GX Pack sequence", "description": "Acknowledgement queue full."},
    320: {"text": "GX Ack", "description": "Guard crossing not acking packets."},
    321: {"text": "GX Pack over", "description": "Guard crossing oversize packet received."},
    322: {"text": "GX Ack num", "description": "Guard crossing wrong ack number."},
    325: {"text": "GX Ack byte", "description": "Guard crossing unknown ack byte."},
    330: {"text": "GX CRC failed", "description": "Guard crossing Bad CRC."},
    340: {"text": "GX Info packet", "description": "Guard crossing info packet received; link not active."},
    350: {"text": "GX Control byte", "description": "Guard crossing unknown control byte."},
    360: {"text": "GX Quality low", "description": "Guard crossing quality indicator too low."},
    370: {"text": "GX Restart", "description": "Guard crossing restarted."},
    421: {"text": "Instrument configuration invalid", "description": "Tried to set invalid state."},
    422: {"text": "Instrument configuration parameter", "description": "Invalid parameter."},
    426: {"text": "Instrument configuration load", "description": "Instrument configuration load failed."},
    510: {"text": "CCO Name bad", "description": "CCO constant name is bad."},
    511: {"text": "RS-232 framing/parity/overrun error", "description": "An error occurred with RS-232 framing/parity/overrun."},
    512: {"text": "RS-232 fatal error", "description": "A fatal error occurred opening the serial port."},
    513: {"text": "RS-232 Configuration error", "description": "A fatal error occurred while configuring the serial port."},
    514: {"text": "Command allowed only with RS-232", "description": "Commands allowed only with the RS-232/Ethernet interface were used inappropriately."},
    520: {"text": "Command line too long", "description": "The command line exceeded 350 characters."},
    521: {"text": "Input buffer overflow", "description": "The input buffer overflowed."},
    522: {"text": "Output buffer overflow", "description": "The output buffer overflowed."},
    531: {"text": "Insufficient memory", "description": "Not enough memory to store requested readings."},
    550: {"text": "Command not allowed in local", "description": "The multimeter received a READ? command while in the local mode."},
    1000: {"text": "Unknown function", "description": "Unknown Function Selection."},
    1001: {"text": "Unknown range", "description": "Unknown Range Selection."},
    1002: {"text": "Unknown CCO", "description": "Unknown Calibration Constant."},
    1003: {"text": "Can’t set NPLC", "description": "Illegal/Unknown NPLC Selection."},
    1004: {"text": "Can’t set trigger", "description": "Illegal/Unknown TRIGGER Selection."},
    1005: {"text": "Can’t get DCV Gains", "description": "Cannot get 1V/10V DC linearization constants."},
    1006: {"text": "Line Freq High", "description": "AC Line frequency too high."},
    1007: {"text": "Line Freq Low", "description": "AC Line frequency too low."},
    1008: {"text": "Write CCO failure", "description": "Calibration Constant write failed."},
    65535: {"text": "Unknown", "description": "Unknown Error."},

    # Table 34. Ethernet/IEEE-488 Configuration Errors
    560: {"text": "GPIB fatal error", "description": "A fatal error occured opening the GPIB port."},
    570: {"text": "GPIB primary address", "description": "An error occured attempting to set the GPIB primary address."},
    572: {"text": "GPIB Read", "description": "An error occurred while attempting to read characters from the GPIB port."},
    580: {"text": "EDVR GPIB", "description": "DOS Error."},
    581: {"text": "ECIC GPIB", "description": "Specified GPIB Interface Board is Not Active Controller."},
    583: {"text": "EADR GPIB", "description": "Interface Board has not been addressed properly."},
    584: {"text": "EARG GPIB", "description": "Invalid argument."},
    585: {"text": "ESAC GPIB", "description": "Specified GPIB Interface Board is not System Controller."},
    586: {"text": "EABO GPIB", "description": "I/O operation aborted (timed out)."},
    587: {"text": "ENEB GPIB", "description": "Non-existent GPIB board."},
    588: {"text": "EOIP GPIB", "description": "Routine not allowed during asynchronous I/O operation."},
    589: {"text": "ECAP GPIB", "description": "No capability for operation."},
    590: {"text": "EFSO GPIB", "description": "File System Error."},
    591: {"text": "EBUS GPIB", "description": "Command byte transfer error."},
    592: {"text": "ESTB GPIB", "description": "Serial poll status byte lost."},
    593: {"text": "ESRQ GPIB", "description": "SRQ stuck in ON position."},
    594: {"text": "ETAB GPIB", "description": "Table problem."},
    801: {"text": "ENET Port number", "description": "Port value is out of range (1024 to 65535)."},
    802: {"text": "ENET Server", "description": "Could not open the ethernet port."},
    803: {"text": "ENET Timeout", "description": "Time-out occured while opening the ethernet port."},


    # Table 35. Calibration Errors
    701: {"text": "CAL Secure Code", "description": "Invalid characters in calibration secure code."},
    702: {"text": "CAL Secure", "description": "Calibration secured."},
    703: {"text": "CAL Secure code", "description": "Invalid secure code."},
    704: {"text": "CAL Secure code too long", "description": "Secure code too long."},
    706: {"text": "CAL Invalid step number", "description": "Invalid calibration step number."},
    707: {"text": "CAL Reference", "description": "Calibration reference value out of tolerance."},
    708: {"text": "CAL Not calibrating", "description": "CAL? only works if you are calibrating."},
    709: {"text": "CAL Abort", "description": "Calibration aborted."},
    710: {"text": "CAL Sequence", "description": "Calibration steps out-of-sequence."},
    711: {"text": "CAL No measurement", "description": "No measurements taken during calibration."},
    712: {"text": "CAL Overload", "description": "Overload at input during calibration."},
    713: {"text": "CAL Too far", "description": "Calibration measurements out-of-tolerance."},
    714: {"text": "CAL Math", "description": "Math error during calibration."},
    715: {"text": "CAL Timeout", "description": "Timeout error during calibration."},

    # Miscellaneous
    65535: {"text": "Unknown", "description": "Unknown Error."},
}
